#ifndef GAUIL_DRAW_HPP
#define GAUIL_DRAW_HPP

#include <any>
#include <cstdint>
#include <functional>
#include <optional>
#include <string>

#include <GaUIL/Color.hpp>
#include <GaUIL/Corners.hpp>
#include <GaUIL/Edges.hpp>
#include <GaUIL/Rect.hpp>
#include <GaUIL/Text.hpp>
#include <GaUIL/Vector2.hpp>


namespace gauil {
    struct Vertex {
        Vector2f position;
    };
    typedef void(TriangleDrawCallback)(const Vertex* vertices, size_t vertexCount, const Color& color, const std::any& userData);
    typedef void(RectDrawCallback)(const FRect& rect, const Color& color, const std::any& userData);
    /// @brief Callback to load a texture a pixel array
    /// @note Pixels are formatted as 8 bit RGBA
    typedef std::optional<std::any>(LoadTextureCallback)(const uint8_t* pixels, int width, int height);
    /// @brief This callback is used to unload the texture generated by the LoadTextureCallback
    /// @note This callback is completely optional if you're using something like a shared pointer
    typedef void (UnloadTextureCallback)(const std::any& texture);

    typedef void(DrawTextureCallback)(const std::any& texture, const gauil::Vector2f& position, const gauil::Vector2f& scale, const Color& color, const std::any& userData);

    void setTriangleListDrawFn(const std::function<TriangleDrawCallback>& fn);
    std::function<TriangleDrawCallback> getTriangleListDrawFn();
    void setTriangleFanDrawFn(const std::function<TriangleDrawCallback>& fn);
    std::function<TriangleDrawCallback> getTriangleFanDrawFn();
    void setTriangleStripDrawFn(const std::function<TriangleDrawCallback>& fn);
    std::function<TriangleDrawCallback> getTriangleStripDrawFn();

    void setRectDrawFn(const std::function<RectDrawCallback>& fn);
    std::function<RectDrawCallback> getRectDrawFn();

    void setLoadTextureFn(const std::function<LoadTextureCallback>& fn);
    std::function<LoadTextureCallback> getLoadTextureFn();

    void setUnloadTextureFn(const std::function<UnloadTextureCallback>& fn);
    std::function<UnloadTextureCallback> getUnloadTextureFn();

    void setDrawTextureFn(const std::function<DrawTextureCallback>& fn);
    std::function<DrawTextureCallback> getDrawTextureFn();


    void setDrawUserData(const std::any& userData);
    std::any getDrawUserData();

    // Default font should be set before initialization
    void setDefaultFont(const std::string& file);
    void setDefaultFont(const uint8_t* data, size_t length);
    IFont* getDefaultFont();

    namespace priv {
        void drawTriangleList(const Vertex* vertices, size_t vertexCount, const Color& color);
        void drawTriangleFan(const Vertex* vertices, size_t vertexCount, const Color& color);
        void drawTriangleStrip(const Vertex* vertices, size_t vertexCount, const Color& color);

        void drawRect(const FRect& rect, const Color& color);
        void drawText(const Vector2f& pos, uint fontSize, float scale, const std::string& text, const Color& color, IFont* font);

        Vector2f measureText(const std::string& string, uint fontSize, IFont* font);

        std::optional<std::any> loadTexture(const uint8_t* pixels, int width, int height);
        void unloadTexture(const std::any& texture);
        void drawTexture(const std::any& texture, const gauil::Vector2f& position, const gauil::Vector2f& scale, const Color& color);

        void roundRect(const FRect& rect, const FCorners& cornerRadius, const FEdges& edges, const Color& backgroundColor, const Color& borderColor);
    }
}


#endif
