
#ifndef GAUIL_GAUIL_H
#define GAUIL_GAUIL_H
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

typedef enum gauil_LayoutType {
    GAUIL_LAYOUT_PIXELS,
    GAUIL_LAYOUT_PERCENT,
    GAUIL_LAYOUT_OTHER_LAYOUT,
} gauil_LayoutType;
typedef struct gauil_Layout {
    gauil_LayoutType type;
    float value;
    bool scaleWithOpposingAxis;
}gauil_Layout;
typedef struct gauil_Layout2D {
    gauil_Layout x;
    gauil_Layout y;
}gauil_Layout2D;
typedef struct gauil_Vector2f {
    float x;
    float y;
} gauil_Vector2f;
typedef struct gauil_Vector2i {
    int x;
    int y;
} gauil_Vector2i;
typedef struct gauil_Vector2u {
    unsigned int x;
    unsigned int y;
} gauil_Vector2u;
typedef struct  gauil_Vertex {
    gauil_Vector2f position;
} gauil_Vertex;
typedef struct  gauil_Color {
    uint8_t r;
    uint8_t g;
    uint8_t b;
    uint8_t a;
}  gauil_Color;
typedef  struct  gauil_FRect {
    float x;
    float y;
    float w;
    float h;
}  gauil_FRect;
#define GAUIL_PIXELS(value) (gauil_Layout){GAUIL_LAYOUT_PIXELS, value, false}
#define GAUIL_PERCENT(value) (gauil_Layout){GAUIL_LAYOUT_PERCENT, value, false}
#define GAUIL_OTHER_LAYOUT (gauil_Layout){GAUIL_LAYOUT_OTHER_LAYOUT, 0, false}

typedef void(gauil_TriangleDrawCallback)(const  gauil_Vertex* vertices, size_t vertexCount, gauil_Color color, void* userData);
typedef void(gauil_RectDrawCallback)(gauil_FRect rect, gauil_Color color, void* userData);

typedef gauil_Vector2u(gauil_GetWindowSizeCallback)();
/// @brief Callback to get the mouse position
/// @note Make sure the position is relative to the window/surface you're drawing the UI to
typedef gauil_Vector2i(gauil_GetMousePositionCallback)();
/// @brief Callback to check if the mouse is pressed
/// @note Use functions like sf::Mouse::isButtonPressed or SDL_GetMouseState to check the mouse. DO NOT USE EVENTS
/// @note Make sure that this function returns false if the window is not focused
typedef bool(gauil_IsMousePressedCallback)();

/// @brief Callback to load a texture a pixel array
/// @note Pixels are formatted as RGBA 8 bit per channel
typedef void* (gauil_LoadTextureCallback)(const uint8_t* pixels, int width, int height);
/// @brief This callback is used to unload the texture generated by the LoadTextureCallback
/// @note This callback is completely optional if you're using something like a shared pointer but is made mandatory since you're using the C API
typedef void (gauil_UnloadTextureCallback)(void* texture);

typedef void(gauil_DrawTextureCallback)(void* texture, gauil_Vector2f position, gauil_Vector2f scale, gauil_Color color, void* userData);




#ifndef GAUIL_C_HEADER_IMPL
void gauil_setTriangleListDrawFn(gauil_TriangleDrawCallback* callback);
void gauil_setTriangleStripDrawFn(gauil_TriangleDrawCallback* callback);
void gauil_setTriangleFanDrawFn(gauil_TriangleDrawCallback* callback);
void gauil_setRectDrawFn(gauil_RectDrawCallback* callback);


void gauil_setWindowSizeFn(gauil_GetWindowSizeCallback* callback);
void gauil_setMousePositionFn(gauil_GetMousePositionCallback* callback);
void gauil_setMouseDownFn(gauil_IsMousePressedCallback* callback);
void gauil_setLoadTextureFn(gauil_LoadTextureCallback* callback);
void gauil_setUnloadTextureFn(gauil_UnloadTextureCallback* callback);
void gauil_setDrawTextureFn(gauil_DrawTextureCallback* callback);

void gauil_setDrawUserData(void* userData);
void gauil_setDefaultFontFromFile(const char* file);
void gauil_setDefaultFontFromMemory(const uint8_t* data, size_t size);
void gauil_init();
void gauil_cleanup();
void gauil_update();
void gauil_draw();
bool gauil_loadStyle(const char* string);
bool gauil_loadFontFromFile(const char* file, const char* referenceName);
bool gauil_loadFontFromMemory(const uint8_t* data, size_t size, const char* referenceName);

gauil_Layout gauil_scaleWithOpposingAxis(gauil_Layout layout);
void gauil_pushSubRect(gauil_Layout2D position, gauil_Layout2D size);
void gauil_popSubRect();

bool gauil_button(const char* text, gauil_Layout2D position, gauil_Layout2D size);
/// Leave style blank to use default    
void gauil_panel(gauil_Layout2D position, gauil_Layout2D size, const char* style);
void gauil_label(const char* text, gauil_Layout2D position, gauil_Layout2D size);
void gauil_checkBox(bool* value, const char* style, gauil_Layout2D position, gauil_Layout2D size);
void gauil_slider(float* value, const char* style, float min, float max, gauil_Layout2D position, gauil_Layout2D size);
#endif

#endif

